#!/usr/bin/env node
const jsdocApi = require('jsdoc-api');
const fs = require('fs');
const fancyLog = require('fancy-log');

const files = fs.readdirSync('./src/js').map(function(file) {
    return './src/js/' + file;
});

const explainations = jsdocApi.explainSync({
    files: files
});

let prototypes = [];

for(let prototype of explainations) {
    if( prototype.undocumented === true || prototype.kind === 'package' ) {
        continue;
    }

    let name = prototype.name;

    if( 'returns' in prototype === false ) {
        fancyLog.warn('the prototype ' + name + '.js is missing a @returns doc');
        fancyLog.warn('skipping this prototype');

        continue;
    }

    let returns = prototype.returns[0].type.names.join(' or ');
    let throws = prototype.exceptions;
    let params = 'params' in prototype ? prototype.params : [];
    let summary = prototype.summary;
    let description = prototype.description;
    let start_line = prototype.meta.lineno;
    let links = prototype.see;
    let options = [];
    let examples = [];
    let since = prototype.since;

    for( let example of prototype.examples ) {
        examples.push(`
            <pre class="code" data-lang="javascript"><code class="javascript">${example}</code></pre>
        `);
    }

    for( let param of params ) {
        let type = param.type.names.join(' or ');
        let name = param.name.replace(/^[\w]+\./, '<span class="text-secondary">$&</span>');
        let description = param.description;
        let defaultvalue = 'defaultvalue' in param ? param.defaultvalue : '';

        options.push(`
            <tr>
                <td>${type}</td>
                <td>${name}</td>
                <td>${defaultvalue}</td>
                <td>${description}</td>
            </tr>
        `);
    }

    if( options.length > 0 ) {
        options = `
            <table class="table table-scroll table-striped table-hover">
                <thead>    
                    <tr>
                        <th>Type</th>
                        <th>Name</th>
                        <th>Default</th>
                        <th>Description</th>
                    </tr>
                </thead>
                <tbody>
                    ${options.join('')}
                </tbody>
            </table>
        `;
    }
    else {
        options = `No options available.`;
    }

    prototypes.push(`
        <div class="column col-sm-12 col-md-6 col-lg-6 col-xl-4 col-4">
            <div class="panel" id="${name}">
                <div class="panel-header">
                    <div class="panel-title">
                        <a href="#${name}" class="h5">#</a>
                        <span class="text-bold"><strong>${name}</strong></span>
                        <span class="chip float-right">≥ ${since}</span>
                        <p>${summary}</p>
                    </div>
                </div>
                <div class="panel-nav">
                    <ul class="tab tab-block">
                        <li class="tab-item active" data-display="${name}-description">
                            <a href="javascript:;">Description</a>
                        </li>
                        <li class="tab-item" data-display="${name}-options">
                            <a href="javascript:;">Options</a>
                        </li>
                        <li class="tab-item" data-display="${name}-example">
                            <a href="javascript:;">Example</a>
                        </li>
                    </ul>
                </div>
                <div class="panel-body">
                    <div class="tab-item-content" id="${name}-description">
                        <div><br /></div>
                        <div class="h5">Returns</div>    
                        <p>${returns}</p>
                    </div>                    
                    <div class="tab-item-content d-hide" id="${name}-options">
                        ${options}
                    </div>
                    <div class="tab-item-content d-hide" id="${name}-example">
                        ${examples.join('')}
                    </div>
                </div>
                <div class="panel-footer">
                    <div class="btn-group float-right">
                        <button class="btn btn-primary cdn" data-url="${links[0]}">CDN&nbsp; <i class="icon-docs"></i></button>
                        <a href="${links[1]}#L${start_line}" class="btn">Source&nbsp; <i class="icon-action-redo"></i></a>
                        <a href="${links[2]}" class="btn">Tests&nbsp; <i class="icon-action-redo"></i></a>
                    </div>	
                </div>
            </div>
        </div>
    `);

    fancyLog.info('generated documentation for ' + name + '.js');
}

let page = `
    <!DOCTYPE html>
    <html lang="en">
        <head>
            <meta charset="utf-8">
            <meta name="description" content="Supercharge your Javascript!" />
            <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
            <title>Prototype Storm - Supercharge your Javascript!</title>
            <link rel="stylesheet" type="text/css" href="https://unpkg.com/spectre.css/dist/spectre.min.css">
            <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/simple-line-icons/2.4.1/css/simple-line-icons.min.css">
            <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/simple-line-icons/2.4.1/fonts/Simple-Line-Icons.eot">
            <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/simple-line-icons/2.4.1/fonts/Simple-Line-Icons.svg">
            <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/simple-line-icons/2.4.1/fonts/Simple-Line-Icons.ttf">
            <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/simple-line-icons/2.4.1/fonts/Simple-Line-Icons.woff">
            <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/simple-line-icons/2.4.1/fonts/Simple-Line-Icons.woff2">
            <link rel="stylesheet" type="text/css" href="/prototype-storm/framework/highlightjs/9.12.0/css/atom-one-light.css"  />
            <link rel="stylesheet" href="/prototype-storm/css/spectre-orange-theme.css" />
        </head>
        <body>
            <header class="navbar">
                <section class="navbar-section">
                    <div class="dropdown">
                        <a class="btn btn-link btn-menu dropdown-toggle show-sm" tabindex="0"><i class="icon-menu"></i>&nbsp;</a>
                        <ul class="menu">
                            <li class="menu-item">
                                <a href="/prototype-storm/installation" disabled="true" tabindex="-1">Installation</a>
                            </li>
                            <li class="menu-item">
                                <a href="https://github.com/stellar-labs/prototype-storm">GitHub &nbsp;<i class="icon-social-github"></i></a>
                            </li>
                        </ul>
                    </div>
                    <a href="/prototype-storm" class="navbar-brand mr-2 text-uppercase">
                        Prototype Storm
                    </a>
                    <a href="/prototype-storm/installation" disabled="true" tabindex="-1" class="btn btn-link hide-sm">Installation</a>
                    <a href="https://github.com/stellar-labs/prototype-storm" class="btn btn-link hide-sm">GitHub&nbsp; <i class="icon-social-github"></i></a>
                </section>
                <section class="navbar-section">
                    <div class="input-group input-inline">
                        <div class="form-group">
                            <select class="form-select">
                                <option>0.1.0</option>
                            </select>
                        </div>
                    </div>
                </section>
            </header>
            <div class="divider"></div>
            <div class="container">
                <div class="columns">
                    <div class="column col-12">
                        <br />
                        <h2>Supercharge your Javascript!</h2>
                    </div>
                    <div class="column col-12">
                        <br />
                        <input class="form-input" type="text" placeholder="search">
                        <br />
                    </div>
                    <div>
                    </div>
                    ${prototypes.join('')}
                </div>
            </div>
            <script type="text/javascript" src="/prototype-storm/framework/highlightjs/9.12.0/js/highlightjs.min.js"></script>
            <script type="text/javascript" src="/prototype-storm/js/spectrecss-tabs.js"></script>
            <script type="text/javascript" src="/prototype-storm/js/highlightjs.js"></script>
        </body>
    </html>
`;

try {
    fs.writeFileSync('./docs/index.html', new Buffer(page));
}
catch( error ) {
    console.error(error);
}
