#!/usr/bin/env node
const jsdocApi = require('jsdoc-api');
const fs = require('fs');
const fancyLog = require('fancy-log');
const sentenceCase = require('sentence-case');
const kebabCase = require('kebab-case');
const moment = require('moment');

function toFixed(num, fixed) {
    var re = new RegExp('^-?\\d+(?:\.\\d{0,' + (fixed || -1) + '})?');
    return num.toString().match(re)[0];
}

const files = fs.readdirSync('./src/js').map(function(file) {
    return './src/js/' + file;
});

const checksums = JSON.parse(fs.readFileSync('./dist/checksum.json').toString());

const explainations = jsdocApi.explainSync({
    files: files
});

let prototypes = [];
let prototype_links = [];
let meta_keywords = [];
let prototype_count = 0;

for(let prototype of explainations) {
    if( prototype.undocumented === true || prototype.kind === 'package' ) {
        continue;
    }

    let name = prototype.name;

    let size = (fs.statSync('./dist/' + kebabCase(name) + '.min.js.gz').size / 1000);
    
    size = size >= 1 ? size.toFixed(0) : toFixed(size, 1);    

    meta_keywords.push(sentenceCase(name).toLocaleLowerCase());

    if( 'returns' in prototype === false ) {
        fancyLog.warn('the prototype ' + name + '.js is missing a @returns doc');
        fancyLog.warn('skipping this prototype');

        continue;
    }

    let returns = prototype.returns[0].type.names.join(' or ');
    let throws = prototype.exceptions;
    let params = 'params' in prototype ? prototype.params : [];
    let summary = prototype.summary;
    let description = prototype.description;
    let start_line = prototype.meta.lineno;
    let links = prototype.see;
    let options = [];
    let examples = [];
    let since = prototype.since;

    // fetch checksum value for the current file
    const key = 'dist/' + kebabCase(name) + '.min.js';
    
    if( key in checksums === false ) {
        fancyLog.error('could not find the hash of the file ' + name);
    
        return;
    }

    checksum = checksums[key];

    for( let example of prototype.examples ) {
        examples.push(`
            <pre class="code" data-lang="javascript"><code class="javascript">${example}</code></pre>
        `);
    }

    for( let param of params ) {
        if( param.type === undefined ) {
            fancyLog.error('the prototype ' + prototype.name + ' has no type for the parameter ' + param.name);

            return;
        }
        
        let type = param.type.names.join(' or ');
        let name = param.name.replace(/^[\w]+\./, '<span class="text-secondary">$&</span>');
        let description = param.description;
        let defaultvalue = 'defaultvalue' in param ? param.defaultvalue : '';

        options.push(`
            <tr>
                <td>${type}</td>
                <td>${name}</td>
                <td>${defaultvalue}</td>
                <td>${description}</td>
            </tr>
        `);
    }

    if( options.length > 0 ) {
        options = `
            <table class="table table-scroll table-striped table-hover">
                <thead>    
                    <tr>
                        <th>Type</th>
                        <th>Name</th>
                        <th>Default</th>
                        <th>Description</th>
                    </tr>
                </thead>
                <tbody>
                    ${options.join('')}
                </tbody>
            </table>
        `;
    }
    else {
        options = `No options available.`;
    }

    prototype_links.push(`
        <li class="menu-item">
            <a href="#${name}">${name}</a>
        </li>
    `);

    prototypes.push(`
        <div class="column col-sm-12 col-md-6 col-lg-6 col-xl-4 col-4" itemscope itemtype="http://schema.org/SoftwareSourceCode">
            <div class="d-none" itemprop="codeSampleType">full solution</div>
            <div class="d-none" itemprop="programmingLanguage">javascript</div>
            <div class="d-none" itemprop="runtimePlatform">web</div>
            <div class="d-none" itemprop="codeRepository">${links[1]}#L${start_line}</div>
            <div class="panel" id="${name}">
                <div class="panel-header">
                    <div class="panel-title" itemscope itemtype="http://schema.org/Thing">
                        <a href="#${name}" class="h5">#</a>
                        <span class="text-bold"><strong itemprop="name">${name}</strong></span>
                        <span class="chip float-right">≥ ${since}</span>
                        <p itemprop="description">${summary}</p>
                    </div>
                </div>
                <div class="panel-nav">
                    <ul class="tab tab-block">
                        <li class="tab-item active" data-display="${name}-description">
                            <a href="javascript:;">Description</a>
                        </li>
                        <li class="tab-item" data-display="${name}-options">
                            <a href="javascript:;">Options</a>
                        </li>
                        <li class="tab-item" data-display="${name}-example">
                            <a href="javascript:;">Example</a>
                        </li>
                    </ul>
                </div>
                <div class="panel-body" itemscope itemtype="http://schema.org/CreativeWork">
                    <div class="tab-item-content" id="${name}-description">
                        <div><br /></div>
                        <div class="h5">Returns</div>    
                        <p>${returns}</p>
                    </div>                    
                    <div class="tab-item-content d-hide" id="${name}-options">
                        ${options}
                    </div>
                    <div class="tab-item-content d-hide" id="${name}-example" itemprop="exampleOfWork">
                        ${examples.join('')}
                    </div>
                </div>
                <div class="panel-footer">
                    <div class="btn-group float-right">
                        <button class="btn btn-primary cdn" data-url="${links[0]}" data-checksum="${checksum}">CDN (${size} Ko)&nbsp; <i class="icon-docs"></i></button>
                        <a href="${links[1]}#L${start_line}" class="btn">Source&nbsp; <i class="icon-action-redo"></i></a>
                        <a href="${links[2]}" class="btn">Tests&nbsp; <i class="icon-action-redo"></i></a>
                    </div>	
                </div>
            </div>
        </div>
    `);

    prototype_count++;

    fancyLog.info('generated documentation for ' + name + '.js');
}

const now = new Date();

const meta_revised = new Intl.DateTimeFormat('en-US', {
	weekday: 'long',
  month: 'long',
  day: 'numeric',
  year: 'numeric',
  hour: 'numeric',
  minute: 'numeric'
}).format(now);

const baseline = 'Supercharge your Javascript!';

let page = `
    <!DOCTYPE html>
    <html lang="en">
        <head>
            <meta charset="utf-8">
            <meta name="description" content="${baseline}" />
            <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
            <meta name="keywords" content="${meta_keywords.join(',')}" />
            <meta name="subject" content="Javascript prototypes to help you code less, and better." />
            <meta name="revised" content="${meta_revised}" />
            <meta name="url" content="https://stellar-labs.github.io/prototype-storm" />
            <meta name="identifier-URL" content="https://stellar-labs.github.io/prototype-storm" />
            <meta name="pagename" content="${baseline}" />
            <meta name="coverage" content="Worldwide" />
            <meta name="distribution" content="Global" />
            <meta name="rating" content="General" />
            <meta name="target" content="all" />
            <meta name="HandheldFriendly" content="True" />
            <meta name="date" content="${meta_revised}" />
            <meta name="DC.title" content="${baseline}" />
            <meta name="apple-mobile-web-app-title" content="Prototype Storm - ${baseline}">
            <meta name="apple-mobile-web-app-capable" content="yes" />
            <meta name="apple-touch-fullscreen" content="yes" />
            <title>Prototype Storm - ${baseline}</title> 
            <link rel="canonical" href="https://stellar-labs.github.io/prototype-storm" />
            <link rel="stylesheet" type="text/css" href="https://unpkg.com/spectre.css/dist/spectre.min.css">
            <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/simple-line-icons/2.4.1/css/simple-line-icons.min.css">
            <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/simple-line-icons/2.4.1/fonts/Simple-Line-Icons.eot">
            <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/simple-line-icons/2.4.1/fonts/Simple-Line-Icons.svg">
            <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/simple-line-icons/2.4.1/fonts/Simple-Line-Icons.ttf">
            <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/simple-line-icons/2.4.1/fonts/Simple-Line-Icons.woff">
            <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/simple-line-icons/2.4.1/fonts/Simple-Line-Icons.woff2">
            <link rel="stylesheet" type="text/css" href="/prototype-storm/framework/highlightjs/9.12.0/css/atom-one-light.css"  />
            <link rel="stylesheet" href="/prototype-storm/css/spectre-orange-theme.css" />
            <link rel="manifest" href="/manifest.webmanifest" />
        </head>
        <body>
            <header class="navbar">
                <section class="navbar-section">
                    <div class="dropdown">
                        <a class="btn btn-link btn-menu dropdown-toggle" tabindex="0"><i class="icon-menu"></i>&nbsp;</a>
                        <ul class="menu sidenav-menu">
                            <li class="menu-item">
                                <a href="/prototype-storm/installation" disabled="true" tabindex="-1">Installation</a>
                            </li>
                            <li class="menu-item">
                                <a href="https://github.com/stellar-labs/prototype-storm">GitHub &nbsp;<i class="icon-social-github"></i></a>
                            </li>
                            <li class="divider" data-content="Prototypes (${prototype_count})"></li>
                            ${prototype_links.join('')}
                        </ul>
                    </div>
                    <a href="/prototype-storm" class="navbar-brand mr-2 text-uppercase">
                        Prototype Storm
                    </a>
                </section>
                <section class="navbar-section">
                    <div class="input-group input-inline">
                        <div class="form-group">
                            <select class="form-select" aria-label="Version">
                                <option>0.1.0</option>
                            </select>
                        </div>
                    </div>
                </section>
            </header>
            <div class="container">
                <div class="columns">
                    <div class="column col-12">
                        <br />
                        <h2>Supercharge your Javascript!</h2>
                    </div>
                    <div class="column col-12">
                        <br />
                        <input id="search" class="form-input" type="text" placeholder="search" aria-label="Search">
                        <br />
                    </div>
                    <div>
                    </div>
                    
                </div>
            </div>
            <main class="container">
                <div class="columns">
                    ${prototypes.join('')}
                </div>
            </main>
            <div id="toast" class="toast toast-primary">
                <i class=""></i>&nbsp; <span></span>
            </div>
            <script type="text/javascript" src="/prototype-storm/framework/highlightjs/9.12.0/js/highlightjs.min.js"></script>
            <script type="text/javascript" src="/prototype-storm/js/spectrecss-tabs.js"></script>
            <script type="text/javascript" src="/prototype-storm/js/highlightjs.js"></script>
            <script type="text/javascript" src="/prototype-storm/js/filter-prototypes.js"></script>
            <script type="text/javascript" src="/prototype-storm/js/display-toast.js"></script>
            <script type="text/javascript" src="/prototype-storm/js/copy-to-clipboard.js"></script>
            <script type="text/javascript" src="/prototype-storm/js/on-click-copy-cdn.js"></script>
            <script async src="https://www.googletagmanager.com/gtag/js?id=UA-119139201-1"></script>
            <script type="text/javascript" src="/prototype-storm/js/google-analytics.js"></script>
        </body>
    </html>
`;

try {
    fs.writeFileSync('./docs/index.html', new Buffer(page));
}
catch( error ) {
    fancyLog.error('unable to save the documentation (detail: ' + error + ')');
}

const sitemap_last_mod = moment().format('YYYY-MM-DD');
const sitemap = `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
   <url>
        <loc>https://stellar-labs.github.io/prototype-storm</loc>
        <lastmod>${sitemap_last_mod}</lastmod>
   </url>
</urlset>`;

try {
    fs.writeFileSync('./docs/sitemap.xml', new Buffer(sitemap));
}
catch( error ) {
    fancyLog.error('unable to save the XML (detail: ' + error + ')');
}

fancyLog.info('updated the XML file');